// helps;

export const EVENTS_FETCHING = 'EVENTS_FETCHING';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';
export const EVENTS_FAILED = 'EVENTS_FAILED';

export const NEWS_FETCHING = 'NEWS_FETCHING';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAILED = 'NEWS_FAILED';

export const NEWSCATS_FETCHING = 'NEWSCATS_FETCHING';
export const NEWSCATS_SUCCESS = 'NEWSCATS_SUCCESS';
export const NEWSCATS_FAILED = 'NEWSCATS_FAILED';

export const ASSOCIATIONS_FETCHING = 'ASSOCIATIONS_FETCHING';
export const ASSOCIATIONS_SUCCESS = 'ASSOCIATIONS_SUCCESS';
export const ASSOCIATIONS_FAILED = 'ASSOCIATIONS_FAILED';

export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const PROCATS_FETCHING = 'PROCATS_FETCHING';
export const PROCATS_SUCCESS = 'PROCATS_SUCCESS';
export const PROCATS_FAILED = 'PROCATS_FAILED';

export const ADVERTISE_FETCHING = 'ADVERTISE_FETCHING';
export const ADVERTISE_SUCCESS = 'ADVERTISE_SUCCESS';
export const ADVERTISE_FAILED = 'ADVERTISE_FAILED';

export const USER_FETCHING = 'USER_FETCHING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';
